### PR TITLE
Port Mersi-2 L1b reader for Polar2Grid 3.0

### LINKED ISSUE #318: Re-add legacy P2G readers from Satpy implementations
The below list is every reader that we provided in the previous version of Polar2Grid and still want to support. While #269 deals with converting P2G legacy readers to a Satpy implementation, this issue deals with making sure P2G has access to Satpy readers to access reading functionality that was available previously. For example, Satpy already has a VIIRS SDR and VIIRS L1b reader, but these weren't available in the normal Polar2Grid interfaces and providing the same (or very similar) set of defaults and products. For completeness all readers are listed below:

- [x] VIIRS SDR
- [x] VIIRS L1b
- [x] MODIS L1b
- [x] AVHRR (AAPP)
- [x] AMSR2 L1b
- [x] NUCAPS
- [x] MiRS
- [x] ACSPO SST
- [x] CLAVR-x
- [x] VIIRS EDR Active Fires
- [x] VIRR L1b
- [x] MERSI-2 L1b

### PR DESCRIPTION
**Pull request by joleenf**
Closes #318 for the mersi-2 reader.  Tested geotiff writing, awips_tiled is not finishing due to memory leaks.

### CODE REVIEW

**Comment by joleenf** [comment]
The awips_tiled reader is very slow with this data.

**Comment by joleenf** [comment]
Sorry, I meant writer.  geotiff is slow, but tiled seemed to help.  I was able to run with the awips_tiled writer and complete the write with two bands at a time on bumi.  I did not try three, at 8 bands (one of Kathy's original tests -p 1 2 3 4 6 7 20 25), the write did not finish for me on my mac, so I tried on bumi.  I did not wait for the process to error, it was taking a long time, so I just started trying a few bands at a time.  If you would like, I could try running the 8 products and timing it.  However, I think this might have less to do with the mersi reader than the resampling and awips writer:
This was the test:
```python glue.py -r mersi2_l1b -w awips_tiled -p 1 2 3 4 6 7 20 25 -g lcc_conus_300 --sector-id LCC --letters --compress -f data/tf2019259173245.FY3D-X_MERSI_0250M_L1B.HDF data/tf2019259173245.FY3D-X_MERSI_1000M_L1B.HDF data/tf2019259173245.FY3D-X_MERSI_GEO1K_L1B.HDF data/tf2019259173245.FY3D-X_MERSI_GEOQK_L1B.HDF -vv
```

**Comment by djhoese** [comment]
I don't remember if we use the mersi data to produce AWIPS tiles. Regardless, we don't want it to be super slow. Any idea if this works in old P2G and how long it takes?

**Comment by joleenf** [comment]
3 minutes 40 sec. I will try running again with new p2g and use time.

**Comment by joleenf** [comment]
At this point, the awips_tiled version is 10 minutes in and nothing has written yet....
``` time python ~/polar2grid/polar2grid/glue.py -r mersi2_l1b -w awips_tiled -p 1 2 3 4 6 7 20 25 -g lcc_conus_300 --sector-id LCC --letters --compress -f /data/users/kathys/test_data/fy3d_mersi/formitch/data/tf2019259173245.FY3D-X_MERSI_0250M_L1B.HDF /data/users/kathys/test_data/fy3d_mersi/formitch/data/tf2019259173245.FY3D-X_MERSI_1000M_L1B.HDF /data/users/kathys/test_data/fy3d_mersi/formitch/data/tf2019259173245.FY3D-X_MERSI_GEO1K_L1B.HDF /data/users/kathys/test_data/fy3d_mersi/formitch/data/tf2019259173245.FY3D-X_MERSI_GEOQK_L1B.HDF -vv
INFO     : Checking products for sufficient output grid coverage (grid: 'lcc_conus_300')...
INFO     : Resampling to 'lcc_conus_300' using 'nearest' resampling...
WARNING  : environment ORGANIZATION not set for .production_location attribute, using hostname
WARNING  : environment ORGANIZATION not set for .production_location attribute, using hostname
WARNING  : environment ORGANIZATION not set for .production_location attribute, using hostname```

**Comment by joleenf** [comment]
Of course, as soon as I give up...11 minutes and 29 seconds.

**Comment by djhoese** [comment]
Can you tell if the same number of tiles/files are produced?

**Comment by joleenf** [comment]
Yes, both product 312 files.

**Pull request merged**
